server:
  tomcat: #tomact 服务器的配置
    relaxed-query-chars: '|,{,},[,]'  #进行get请求到时候 如何参数包含[,{,},] 认为是正常的
  address: 0.0.0.0
  port : 7246

#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://pg:5432/studs
#    username: s336179
#    password:
#    hikari:
#      pool-name: HikariCP
#      minimum-idle: 5
#      maximum-pool-size: 20
#      idle-timeout: 30000
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      auto-commit: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: postgres
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true

  jackson: # json序列号配置
    property-naming-strategy: UPPER_CAMEL_CASE #设置大写开头的命名风格
    date-format: yyyy-MM-dd HH:mm:ss #设置标准的时间格式
    time-zone: Asia/Shanghai #时间对于的时区

jpa:
  database-platform: org.eclipse.persistence.platform.database.PostgreSQLPlatform
  show-sql: false
  properties:
    eclipselink:
      ddl-generation: create-or-extend-tables
      weaving: false
      cache:
        use_second_level_cache: true
        use_query_cache: true
        shared:
          default: true
      logging:
        level: FINE
        level.sql: FINE
        parameters: true
        region:
          factory_class: jcache
      javax:
        cache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
      generate_statistics: true
  open-in-view: false


      # minio 文件存储配置信息
minio:
  endpoint: https://play.min.io
  url: https://play.min.io
  accessKey: Di90Y5IbkdRLdcm5BI4r
  secretKey: 8dzaqIkhFA5WXqWyqrwTO2Mw7p7vpASqBlzjqSHK
  bucketName: is-lab